# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Jesse Kirimi
tagline:             ''
description:         'A software developer from Nairobi Kenya'
url:                 http://kirimijesse.github.io
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Jesse Kirimi
  url:               https://twitter.com/kirimi_jesse
  email:             rimijessse@outlook.com
